name: minex
description: "Minex — Buscaminas retro moderno."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  audioplayers: ^6.8.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^8.1.0
  google_mobile_ads: ^9.0.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  intl: any
  package_info_plus: ^10.2.0
  path_provider: ^2.1.6
  provider: ^6.1.5+1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
